version: "3"
services:

  furikaerin:
    build: .
    container_name: furikaerin
    ports:
      - "3000:3000"
    networks:
      - furikaerin-net
    environment:
      - RAILS_ENV=development
    depends_on:
      - furikaerin-postgres
    restart: always

  furikaerin-postgres:
    image: postgres:9.6
    container_name: furikaerin-postgres
    expose:
      - "5432"
    networks:
      - furikaerin-net
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:

networks:
  furikaerin-net:

